version: '3.2'

networks:
  phalcon-network:
    driver: bridge
services:
  phalcon-db:
    image: postgres:10.8-alpine
    container_name: db_postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:z
    networks:
      - phalcon-network
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: phalcon
    command:
      postgres -c logging_collector=on -c log_destination=stderr -c log_statement=all
  phalcon-web:
    build:
      context: .
      args:
        - env=driver
        - phalcon_version=v3.4.3
    container_name: phalcon_app
    ports:
      - 81:80
    environment:
        XDEBUG_CONFIG: 
          remote_host=host.docker.internal
          remote_port=9000
    volumes:
      - type: bind
        source: ./src/hello_world
        target: /var/www/html
    networks:
      - phalcon-network
    working_dir: /var/www/html
    depends_on:
      - phalcon-db
    links:
      - "phalcon-redis:redis"
  phalcon-redis:
    image: redis:5-alpine
    container_name: db_session_redis
    networks:
      - phalcon-network
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: redis-server --appendonly yes --requirepass Azerty
    volumes:
      - ./redis_data:/data